version: "3.8"

services:
  bookstack:
    image: linuxserver/bookstack:latest
    container_name: bookstack-app
    restart: unless-stopped
    depends_on:
      - bookstack_db
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      APP_URL: ${APP_URL}
      APP_KEY: ${APP_KEY}
      DB_HOST: bookstack_db
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      MAIL_DRIVER: ${MAIL_DRIVER}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
    volumes:
      - bookstack_config:/config
    ports:
      - "6875:80"
    networks:
      - proxy_network

  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack-db
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - bookstack_db_data:/var/lib/mysql
    networks:
      - proxy_network

volumes:
  bookstack_config:
  bookstack_db_data:

networks:
  proxy_network:
    driver: bridge

