version: '3.8'

services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack
    ports:
      - "6875:80"
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # - APP_URL=https://bookstack.edusuc.net
      - APP_URL=https://8b96-98-101-113-220.ngrok-free.app 
      - APP_KEY=base64:6um2Xi48STZ+dqwdHJOCgta1/VKJhdUj4gFjZEfchu4=
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USERNAME=bookstack
      - DB_PASSWORD=bookstack
      - DB_DATABASE=bookstackapp
      - MAIL_DRIVER=smtp
      - MAIL_FROM_NAME=BookStack
      - MAIL_FROM=info@devopseasylearning.com
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=info@devopseasylearning.com
      - MAIL_PASSWORD="Edhfgnurn$@!HDK"
      - MAIL_ENCRYPTION=tls
    volumes:
      - bookstack_config:/config
    networks:
      - proxy_network

  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=bookstack
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=bookstack
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - bookstack_db_data:/var/lib/mysql
    networks:
      - proxy_network

volumes:
  bookstack_config:
  bookstack_db_data:

networks:
  proxy_network:

